name: Build Audio Collection Normalizer

on:
  workflow_dispatch:

jobs:

  build-windows:

    runs-on: windows-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Download FFmpeg (Windows)
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force third_party/windows | Out-Null

          Invoke-WebRequest `
            -Uri https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-essentials.zip `
            -OutFile ffmpeg.zip

          Expand-Archive ffmpeg.zip -DestinationPath ffmpeg

          $exe = Get-ChildItem ffmpeg -Recurse -Filter ffmpeg.exe | Select-Object -First 1

          Copy-Item $exe.FullName third_party/windows/ffmpeg.exe

      - name: Build Windows executable
        run: |
          python build_scripts/build_win.py

      - name: Upload Windows executable
        uses: actions/upload-artifact@v4
        with:
          name: AudioCollectionNormalizer-Windows
          path: windows/AudioCollectionNormalizer/

  build-macos:

    runs-on: macos-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build macOS application
        run: |
          python build_scripts/build_mac.py

      - name: Upload macOS application
        uses: actions/upload-artifact@v4
        with:
          name: AudioCollectionNormalizer-macOS
          path: macos/AudioCollectionNormalizer.app